---
paths:
  home: /
  __about: /about
  __skills: /skills/
  __cv: /cv
  __blog__category__dissertation: /blog/category/dissertation/
  __blog__category__reports: /blog/category/reports/
  __blog__category__portfolio: /blog/category/portfolio/
  __blog__chorister: /blog/chorister/
  __blog__category__updates: /blog/category/updates/
  __contact: /contact
  __terminal: /terminal/
  __blog__dissertation: /blog/dissertation/
  __blog__discipline-good-enough: /blog/discipline-good-enough/
  __blog__it-is-done: /blog/it-is-done/
  __blog__composer: /blog/composer/
  __blog__mid-project-demonstration: /blog/mid-project-demonstration/
  __blog__completing-the-core: /blog/completing-the-core/
  __blog__commercial-viability: /blog/commercial-viability/
  __blog__cooking-on-gas: /blog/cooking-on-gas/
  __blog__choosing-bdd-framework: /blog/choosing-bdd-framework/
  __blog__reading: /blog/reading/
  __blog__following-plan: /blog/following-plan/
  __blog__outline-project-specification: /blog/outline-project-specification/
  __blog__php-frameworks: /blog/php-frameworks/
  __blog__industrial-year-report: /blog/industrial-year-report/
  __blog__category__dissertation__page__2: /blog/category/dissertation/page/2/
  __blog__exploring-suitability-viola-jones-framework-counting-people: /blog/exploring-suitability-viola-jones-framework-counting-people/
  __blog__smartresolution: /blog/smartresolution/
  __blog__commonwealth-games-quiz: /blog/commonwealth-games-quiz/
  __blog__magazine-parentchild-themes: /blog/magazine-parentchild-themes/
  __blog__reff: /blog/reff/
  __blog__voicecouncil-magazine: /blog/voicecouncil-magazine/
  __blog__hover-bike: /blog/hover-bike/
  __blog__3d-solar-system: /blog/3d-solar-system/
  __blog__how-stressed-are-you: /blog/how-stressed-are-you/
  __blog__studentmunch-com: /blog/studentmunch-com/
  __blog__alice-holmes-anthropomorphism: /blog/alice-holmes-anthropomorphism/
  __blog__nhs-winter: /blog/nhs-winter/
  __blog__abermads-co-uk: /blog/abermads-co-uk/
  __blog__tube-spotted: /blog/tube-spotted/
  __blog__radioactive-evolution: /blog/radioactive-evolution/
  __blog__when-do-i-need-a-non-javascript-solution: /blog/when-do-i-need-a-non-javascript-solution/
  __blog__use-requirejs-wordpress-plugins-jquery-ui: /blog/use-requirejs-wordpress-plugins-jquery-ui/
  __blog__high-impact-minimal-effort-cross-browser-testing: /blog/high-impact-minimal-effort-cross-browser-testing/
  __blog__five-line-rule: /blog/five-line-rule/
  __blog__the-pessimistic-ultimatum: /blog/the-pessimistic-ultimatum/
  __blog__how-to-differentiate-between-links: /blog/how-to-differentiate-between-links/
  __blog__stupidly-simple-programming-introduction: /blog/stupidly-simple-programming-introduction/
  __blog__zaatari-refugee-camp-rebuilding-lives-in-the-desert: /blog/zaatari-refugee-camp-rebuilding-lives-in-the-desert/
  __blog__category__updates__page__2: /blog/category/updates/page/2/
  __blog__requirements-features: /blog/requirements-features/
  __blog__building-shoulders-giants: /blog/building-shoulders-giants/
  __blog__clarifying-requirements: /blog/clarifying-requirements/
  __blog__orthodontic-refactoring: /blog/orthodontic-refactoring/
  __blog__localised-css: /blog/localised-css/
  __blog__project-clarified: /blog/project-clarified/
  __blog__identifying-competitors: /blog/identifying-competitors/
  __blog__and-so-it-begins: /blog/and-so-it-begins/
  __blog__does-drm-promote-piracy: /blog/does-drm-promote-piracy/
  __blog__what-is-the-surprise-app-for-blackberry: /blog/what-is-the-surprise-app-for-blackberry/
  __blog__if-humans-were-computer-components-an-analogy: /blog/if-humans-were-computer-components-an-analogy/
  __blog__redesigning-ip-datagrams-for-a-faster-internet: /blog/redesigning-ip-datagrams-for-a-faster-internet/
  __blog__trinary-is-it-the-future: /blog/trinary-is-it-the-future/
  __blog__the-demise-of-blackberry: /blog/the-demise-of-blackberry/
